version: "1"
services:
  db:
    image: postgis/postgis:latest
    restart: always
    networks:
      - "internal"
    ports:
      - "5432:5432"
    env_file:
      - ./env/db.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  portal:
    image: demo-portal-docker:latest
    build: .
    restart: always
    depends_on:
      - "db"
    networks:
      - "internal"
      - "external"
    ports:
        - "80:80"
    env_file:
      - ./env/portal.env
    volumes:
      - ./data/tethys:/var/lib/tethys_persist
networks:
  internal:
    internal: true
  external: