# Default values for postgis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgis/postgis
  tag: 12-3.4
  pullPolicy: IfNotPresent

postgres_user: postgres
postgres_password: 'please_dont_use_default_passwords'
extra_config:
  max_connections: '500'
  shared_buffers: '512MB'
  work_mem: '5MB'
  autovacuum: 'on'

imagePullSecrets:
  - name: gitlab-registry

init_data:
  enabled: false
  repository: docker.aquaveo.com/tethys/kubernetes/init-containers/init_db
  tag: stable
  storage_host: 'storage.example.com'
  storage_port: '22'
  storage_path: '/data/example.tar.bz2'
  storage_user: 'k8s'
  storage_key: |
    -----BEGIN RSA PRIVATE KEY-----
    exampleStorageKEY
    -----END RSA PRIVATE KEY-----
  archive_host: 'db.example.com'
  archive_port: '22'
  archive_path: '/data/archive'
  archive_user: 'root'
  archive_key: |
    -----BEGIN RSA PRIVATE KEY-----
    exampleArchiveKEY
    -----END RSA PRIVATE KEY-----

nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 5432

storageClass:
  storageClassName: ''

PersistentVolumeClaim:
  name: postgis-pv-claim

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 2
    memory: 1Gi

storage_size: 5Gi

nodeSelector: {}

tolerations: []

affinity: {}
