apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tethys-persist-pvc
  labels:
{{ include "tethys-portal.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tethys.workspace_size | quote }}