apiVersion: v1
kind: Service
metadata:
  name: {{ include "tethys-portal.fullname" . }}
  labels:
{{ include "tethys-portal.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: {{ include "tethys-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}