export const moduleMap = {
  "ol/layer/WebGLTile.js": () => import("ol/layer/WebGLTile.js"),
  "ol/layer/Image.js": () => import("ol/layer/Image.js"),
  "ol/layer/Vector.js": () => import("ol/layer/Vector.js"),
  "ol/layer/Tile.js": () => import("ol/layer/Tile.js"),
  "ol/layer/VectorTile.js": () => import("ol/layer/VectorTile.js"),
  "ol/source/VectorTile.js": () => import("ol/source/VectorTile.js"),
  "ol/source/ImageTile.js": () => import("ol/source/ImageTile.js"),
  "ol/source/ImageArcGISRest.js": () => import("ol/source/ImageArcGISRest.js"),
  "ol/source/Vector.js": () => import("ol/source/Vector.js"),
  "ol/source/ImageWMS.js": () => import("ol/source/ImageWMS.js"),
  "ol/source/Raster.js": () => import("ol/source/Raster.js"),
  "ol/format/GeoJSON.js": () => import("ol/format/GeoJSON.js"),
  "ol/style/Style.js": () => import("ol/style/Style.js"),
  "ol/style/Stroke.js": () => import("ol/style/Stroke.js"),
  "ol/style/Fill.js": () => import("ol/style/Fill.js"),
  "ol/format/EsriJSON.js": () => import("ol/format/EsriJSON.js"),
};
