apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.name }}
  labels:
    app.kubernetes.io/name: {{ include "postgis.name" . }}
    helm.sh/chart: {{ include "postgis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClass.storageClassName }}
  storageClassName: {{ .Values.storageClass.storageClassName | quote }}
  {{- end }}    
  resources:
    requests:
      storage: {{ .Values.storage_size | quote }}
