name: Demo Portal Development CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  DOCKER_UPLOAD_URL: tethysplatform/tethys-demo-portal
  TEST_IMAGE: tethys-demo-portal

jobs:
  docker-build:
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_UPLOAD_URL }}:dev . 
          docker tag ${{ env.DOCKER_UPLOAD_URL }}:dev ${{ env.DOCKER_UPLOAD_URL }}:latest
          docker tag ${{ env.DOCKER_UPLOAD_URL }}:dev ${{ env.TEST_IMAGE }}:dev

      - name: Push Docker Images
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ env.DOCKER_UPLOAD_URL }}:dev
          docker push ${{ env.DOCKER_UPLOAD_URL }}:latest

      - name: Skip Push on PRs
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Uploading to Docker Hub is skipped for pull requests."

      - name: Upload Docker Artifact
        uses: ishworkh/container-image-artifact-upload@v2.0.0
        with:
          image: ${{ env.TEST_IMAGE }}:dev
          retention_days: "1"
