name: Demo Portal Stable CI

on:
  push:
    tags:
      - "*"

env:
  DOCKER_UPLOAD_URL: tethysplatform/tethys-demo-portal

jobs:
  docker-build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v1

      - name: Safe Tag
        id: safetag
        run: |
          full_tag="${{ steps.version.outputs.full }}";
          # no "+" characters allowed in Docker tags
          safe_tag="${full_tag//+/-}";
          echo "safetag=$safe_tag" >> $GITHUB_OUTPUT;
          echo $safe_tag;

      - name: Build With Tag
        run: |
          docker build -t ${{ env.DOCKER_UPLOAD_URL }}:${{ steps.safetag.outputs.safetag }} .;
          docker tag ${{ env.DOCKER_UPLOAD_URL }}:${{ steps.safetag.outputs.safetag }} ${{ env.DOCKER_UPLOAD_URL }}:latest

      - name: Push Docker Images
        run: |
          echo "Pushing to docker registry";
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;
          docker push ${{ env.DOCKER_UPLOAD_URL }}:${{ steps.safetag.outputs.safetag }};
          docker push ${{ env.DOCKER_UPLOAD_URL }}:latest

      - name: Upload Docker Artifact
        uses: ishworkh/container-image-artifact-upload@v2.0.0
        with:
          image: ${{ env.DOCKER_UPLOAD_URL }}:${{ steps.safetag.outputs.safetag }}
          retention_days: "1"

